name: Cabinet Dentaire Barthelemy
short_name: Dentiste Barthelemy
markdown: redcarpet
pygments: true
include: ['fr', 'en', 'assets', 'photos', 'fonts']
assets:
  js_compressor:  uglifier
  css_compressor: sass
